CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) DEFAULT NULL,
  name VARCHAR(100) NOT NULL,
  google_id VARCHAR(255) DEFAULT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE xvilo_orders ADD COLUMN IF NOT EXISTS user_id INT DEFAULT NULL AFTER id,
  ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL;
